#! /bin/bash
echo we are on bash version $BASH_VERSION
welcome=hello
name=kekeli
age=67
echo I just wanted to say $welcome
echo my name is $name
echo I am $age years old
echo Tell me your name too
echo Tell me your name too
read -p 'name: ' hisname class
echo $welcome $hisname 
